import { getLast4FromPlate, getStatus, registerVehicle } from "./parking-core.mjs";
const token = process.env.TELEGRAM_BOT_TOKEN;
const allowedChatIds = new Set((process.env.TELEGRAM_ALLOWED_CHAT_IDS || "").split(",").map((value) => value.trim()).filter(Boolean));
if (!token) throw new Error("TELEGRAM_BOT_TOKEN을 .env에 설정해 주세요.");
if (allowedChatIds.size === 0) throw new Error("TELEGRAM_ALLOWED_CHAT_IDS를 .env에 하나 이상 설정해 주세요.");
const endpoint = `https://api.telegram.org/bot${token}`; let offset = 0; let working = false;
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function telegram(method, payload = {}) { let lastError; for (let attempt = 0; attempt < 3; attempt += 1) { try { const response = await fetch(`${endpoint}/${method}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (data.ok) return data.result; throw new Error(`텔레그램 API 오류: ${data.description || method}`); } catch (error) { lastError = error; if (attempt < 2) await sleep(1500 * (attempt + 1)); } } throw lastError; }
function responseText(result) { if (result.status === "completed") return `✅ 할인 등록 완료\n차량: ${result.record.plate || `끝 ${result.record.last4}`}\n${result.record.message}`; if (result.status === "duplicate") return `ℹ️ 이미 등록된 차량입니다\n차량: ${result.record.plate || `끝 ${result.record.last4}`}\n처리: ${new Date(result.record.createdAt).toLocaleString("ko-KR")}`; if (result.status === "invalid") return `⚠️ ${result.message}\n예: 869버6163`; return `❌ 할인 등록 실패\n${result.record?.message || "다시 시도해 주세요."}`; }
async function handle(update) { const message = update.message; const chatId = message?.chat?.id; const text = message?.text?.trim(); if (!chatId || !text || !allowedChatIds.has(String(chatId))) return; if (text === "/start" || text === "/help") return telegram("sendMessage", { chat_id: chatId, text: "차량번호 전체를 보내면 끝 4자리로 관리자 할인을 등록합니다.\n예: 869버6163\n/status: 연동 상태 확인" }); if (text === "/status") { const status = getStatus(); return telegram("sendMessage", { chat_id: chatId, text: status.connected ? `✅ 주차 사이트 연동 준비됨\n${status.siteUrl}` : "⚠️ 주차 사이트 관리자 계정 설정이 필요합니다." }); } const last4 = getLast4FromPlate(text); if (!last4) return telegram("sendMessage", { chat_id: chatId, text: "⚠️ 차량번호 전체를 입력해 주세요.\n예: 869버6163" }); if (working) return telegram("sendMessage", { chat_id: chatId, text: "⏳ 다른 차량을 처리 중입니다. 잠시 후 다시 보내 주세요." }); working = true; try { await telegram("sendMessage", { chat_id: chatId, text: "🔎 차량 조회 및 할인 적용을 시작합니다…" }); await telegram("sendMessage", { chat_id: chatId, text: responseText(await registerVehicle(last4)) }); } finally { working = false; } }
async function start() { try { const pending = await telegram("getUpdates", { timeout: 0 }); if (pending.length) offset = pending.at(-1).update_id + 1; console.log("Telegram parking bot started. Allowed chats:", [...allowedChatIds].join(", ")); } catch (error) { console.error("Telegram initial connection failed; retrying.", error.message); } while (true) { try { const updates = await telegram("getUpdates", { offset, timeout: 25, allowed_updates: ["message"] }); for (const update of updates) { offset = update.update_id + 1; try { await handle(update); } catch (error) { console.error("Telegram message handling failed.", error.message); } } } catch (error) { console.error("Telegram polling failed; retrying.", error.message); await sleep(5000); } } }
start().catch((error) => { console.error(error); process.exitCode = 1; });
